### ISSUE TITLE
Nodes bootstrapped via aws-hosted-cp get stuck with `node.cloudprovider.kubernetes.io/uninitialized` taint

### ISSUE THREAD

**Issue by squizzi** [Mirantis/hmc#290]
While testing `aws-hosted-cp` for our e2e test work in #280 I encountered a situation where nodes that are deployed using the `aws-hosted-cp` template  cannot use CCM resources as they get stuck with the following taint:

```
    taints:
    - effect: NoSchedule
      key: node.cloudprovider.kubernetes.io/uninitialized
      value: "true"
```

Relates to: https://github.com/kubernetes-sigs/cluster-api/issues/9858. https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4618

Stripping the taint allows the test to progress.
