### ISSUE TITLE
Credentials API and CRDs

### ISSUE THREAD

**Issue by a13x5** [Mirantis/hmc#321]
# CRD

**Simple cluster identity reference**

```yaml
apiVersion: hmc.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: azure-cred
spec:
  description: |
    Main Azure cluster credentials
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: azure-cred-identity
    namespace: hmc-system
status:
  state: Ready
```

User must maintain the cluster identity object by itself (i.e. create cluster identity and corresponding secret). The `Credential` object just references the existing cluster identity object.

`.spec.identityRef.namespace` is an optional field which currently only applies to the Azure provider, since all other providers have cluster scoped cluster identity resources.

`.spec.description` (optional) is a free form description of the credentials. Will be also added to print columns, so it will be easier for the user to choose what `Credential` to use.

`.status.state` field signify if any problem appeared with the resource referenced (e.g. it doesn’t exist).

Controller is not responsible for the cluster identity resource and its secret.
