### ISSUE TITLE
Test use of Profile & ClusterProfile on same cluster

### ISSUE THREAD

**Issue by wahabmk** [Mirantis/hmc#452]

**Comment by wahabmk** [comment]
I have a CAPI cluster provisioned with following labels:
```sh
➜  ~ kubectl -n hmc-system get cluster --show-labels
NAME           CLUSTERCLASS   PHASE         AGE   VERSION   LABELS
wali-aws-dev                  Provisioned   93m             app.kubernetes.io/managed-by=Helm,helm.toolkit.fluxcd.io/name=wali-aws-dev,helm.toolkit.fluxcd.io/namespace=hmc-system,sveltos-agent=present
```
I applied the following `ClusterProfile` with `tier=100`:
```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: ingress-nginx
spec:
  tier: 100
  clusterSelector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
  helmCharts:
    - repositoryURL:    https://kubernetes.github.io/ingress-nginx
      repositoryName:   ingress-nginx
      chartName:        ingress-nginx/ingress-nginx
      chartVersion:     4.11.0
      releaseName:      ingress-nginx
      releaseNamespace: ingress-nginx
      helmChartAction:  Install
```

<table>
<tr>
<td> MANAGEMENT CLUSTER </td> <td> TARGET CLUSTER </td>
</tr>
<tr>
<td>

**I see from the `ClusterSummary` object on the Management Cluster that it has been provisioned:**
```sh
➜  ~ kubectl -n hmc-system get clustersummaries.config.projectsveltos.io ingress-nginx-capi-wali-aws-dev -o yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterSummary
...
spec:
  clusterName: wali-aws-dev
  clusterNamespace: hmc-system
  clusterProfileSpec:
    clusterSelector:
      matchLabels:
        app.kubernetes.io/managed-by: Helm
    continueOnConflict: false
    helmCharts:
    - chartName: ingress-nginx/ingress-nginx
      chartVersion: 4.11.0
      helmChartAction: Install
      releaseName: ingress-nginx
      releaseNamespace: ingress-nginx
      repositoryName: ingress-nginx
      repositoryURL: https://kubernetes.github.io/ingress-nginx
    reloader: false
    stopMatchingBehavior: WithdrawPolicies
    syncMode: Continuous
    tier: 100
  clusterType: Capi
status:
  dependencies: no dependencies
  featureSummaries:
  - featureID: Helm
    hash: IdLNIKMne7/UBP4Cv7nSJ4isY/uqT10AXfP2xbkkuVU=
    lastAppliedTime: "2024-10-07T21:12:32Z"
    status: Provisioned
  helmReleaseSummaries:
  - releaseName: ingress-nginx
    releaseNamespace: ingress-nginx
    status: Managing
    valuesHash: Eq4yyx7ALQHto1gbEnwf7jsNxTVy7WuvI5choD2C4SY=
```

</td>
<td>

**I can see that the `ingress-ngnix-controller` deployment is running with 1 pod on the Target Cluster**
```sh
➜  ~ kubectl get pod -A
NAMESPACE        NAME                                        READY   STATUS    RESTARTS   AGE
ingress-nginx    ingress-nginx-controller-5bfc858768-qqqkj   1/1     Running   0          21s
kube-system      aws-cloud-controller-manager-5z8zf          1/1     Running   0          14m
kube-system      calico-kube-controllers-695f6448bd-qkhkd    1/1     Running   0          15m
kube-system      calico-node-7xnkv                           1/1     Running   0          15m
kube-system      calico-node-gxgl5                           1/1     Running   0          15m
kube-system      coredns-6997b8f8bd-g9rqx                    1/1     Running   0          14m
kube-system      coredns-6997b8f8bd-pvm64                    1/1     Running   0          14m
kube-system      ebs-csi-controller-5c9db44f4f-7k4ld         5/5     Running   0          15m
kube-system      ebs-csi-controller-5c9db44f4f-jmmg5         5/5     Running   0          15m
kube-system      ebs-csi-node-rwxbb                          3/3     Running   0          15m
kube-system      ebs-csi-node-w52sd                          3/3     Running   0          15m
kube-system      kube-proxy-dfmxf                            1/1     Running   0          15m
kube-system      kube-proxy-sv5t6                            1/1     Running   0          15m
kube-system      metrics-server-7cc78958fc-nlxv2             1/1     Running   0          15m
projectsveltos   sveltos-agent-manager-67d6ffbd86-4mgwt      1/1     Running   0          15m
```

</td>
</tr>
</table>

Now I apply the following `Profile` object with `tier=90` and change the values to increase replica count to 3:
```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: Profile
metadata:
  name: ingress-nginx
spec:
  tier: 90 # lower means higher priority
  clusterSelector:
    matchLabels:
      helm.toolkit.fluxcd.io/name: wali-aws-dev
      helm.toolkit.fluxcd.io/namespace: hmc-system
  helmCharts:
    - repositoryURL:    https://kubernetes.github.io/ingress-nginx
      repositoryName:   ingress-nginx
      chartName:        ingress-nginx/ingress-nginx
      chartVersion:     4.11.0
      releaseName:      ingress-nginx
      releaseNamespace: ingress-nginx
      helmChartAction:  Install
      values: |
        controller:
          replicaCount: 3
```

<table>
<tr>
<td> MANAGEMENT CLUSTER </td> <td> TARGET CLUSTER </td>
</tr>
<tr>
<td>

**I see from the `ClusterSummary` object on the Management Cluster that it has been provisioned:**
```sh
➜  ~ kubectl -n hmc-system get clustersummaries.config.projectsveltos.io p--ingress-nginx-capi-wali-aws-dev -o yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterSummary
...
spec:
  clusterName: wali-aws-dev
  clusterNamespace: hmc-system
  clusterProfileSpec:
    clusterSelector:
      matchLabels:
        helm.toolkit.fluxcd.io/name: wali-aws-dev
        helm.toolkit.fluxcd.io/namespace: hmc-system
    continueOnConflict: false
    helmCharts:
    - chartName: ingress-nginx/ingress-nginx
      chartVersion: 4.11.0
      helmChartAction: Install
      releaseName: ingress-nginx
      releaseNamespace: ingress-nginx
      repositoryName: ingress-nginx
      repositoryURL: https://kubernetes.github.io/ingress-nginx
      values: |
        controller:
          replicaCount: 3
    reloader: false
    stopMatchingBehavior: WithdrawPolicies
    syncMode: Continuous
    tier: 90
  clusterType: Capi
status:
  dependencies: no dependencies
  featureSummaries:
  - featureID: Helm
    hash: v4iWa1/2jOCvuJgFBCDZwEes8ywTWmsuYmtsilPhPZk=
    lastAppliedTime: "2024-10-07T21:24:49Z"
    status: Provisioned
  helmReleaseSummaries:
  - releaseName: ingress-nginx
    releaseNamespace: ingress-nginx
    status: Managing
    valuesHash: ps9njX/PI6Tholu/uChBVwaU6c8X/xG90snLLccrdnc=
```

</td>
<td>

**I can see that now the `ingress-ngnix-controller` deployment is running with 3 pod on the Target Cluster**
```sh
➜  ~ kubectl get pod -A
NAMESPACE        NAME                                        READY   STATUS    RESTARTS   AGE
ingress-nginx    ingress-nginx-controller-5bfc858768-5lb6j   1/1     Running   0          114s
ingress-nginx    ingress-nginx-controller-5bfc858768-qqqkj   1/1     Running   0          14m
ingress-nginx    ingress-nginx-controller-5bfc858768-rkzg8   1/1     Running   0          114s
kube-system      aws-cloud-controller-manager-5z8zf          1/1     Running   0          28m
kube-system      calico-kube-controllers-695f6448bd-qkhkd    1/1     Running   0          29m
kube-system      calico-node-7xnkv                           1/1     Running   0          29m
kube-system      calico-node-gxgl5                           1/1     Running   0          28m
kube-system      coredns-6997b8f8bd-g9rqx                    1/1     Running   0          28m
kube-system      coredns-6997b8f8bd-pvm64                    1/1     Running   0          28m
kube-system      ebs-csi-controller-5c9db44f4f-7k4ld         5/5     Running   0          29m
kube-system      ebs-csi-controller-5c9db44f4f-jmmg5         5/5     Running   0          29m
kube-system      ebs-csi-node-rwxbb                          3/3     Running   0          28m
kube-system      ebs-csi-node-w52sd                          3/3     Running   0          29m
kube-system      kube-proxy-dfmxf                            1/1     Running   0          29m
kube-system      kube-proxy-sv5t6                            1/1     Running   0          28m
kube-system      metrics-server-7cc78958fc-nlxv2             1/1     Running   0          29m
projectsveltos   sveltos-agent-manager-67d6ffbd86-4mgwt      1/1     Running   0          29m
```

</td>
</tr>
</table>

Now I make the tier even lower on the `ClusterProfile` and set the replica count to 1 in it. Since it's priority is now higher, it should revert the changes made by the `Profile` object:
```yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: ingress-nginx
spec:
  tier: 80
  clusterSelector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
  helmCharts:
    - repositoryURL:    https://kubernetes.github.io/ingress-nginx
      repositoryName:   ingress-nginx
      chartName:        ingress-nginx/ingress-nginx
      chartVersion:     4.11.0
      releaseName:      ingress-nginx
      releaseNamespace: ingress-nginx
      helmChartAction:  Install
      values: |
        controller:
          replicaCount: 1
```

<table>
<tr>
<td> MANAGEMENT CLUSTER </td> <td> TARGET CLUSTER </td>
</tr>
<tr>
<td>

**I see from the `ClusterSummary` object on the Management Cluster that it has been provisioned:**
```sh
➜  ~ kubectl -n hmc-system get clustersummaries.config.projectsveltos.io ingress-nginx-capi-wali-aws-dev -o yaml
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterSummary
...
spec:
  clusterName: wali-aws-dev
  clusterNamespace: hmc-system
  clusterProfileSpec:
    clusterSelector:
      matchLabels:
        app.kubernetes.io/managed-by: Helm
    continueOnConflict: false
    helmCharts:
    - chartName: ingress-nginx/ingress-nginx
      chartVersion: 4.11.0
      helmChartAction: Install
      releaseName: ingress-nginx
      releaseNamespace: ingress-nginx
      repositoryName: ingress-nginx
      repositoryURL: https://kubernetes.github.io/ingress-nginx
      values: |
        controller:
          replicaCount: 1
    reloader: false
    stopMatchingBehavior: WithdrawPolicies
    syncMode: Continuous
    tier: 80
  clusterType: Capi
status:
  dependencies: no dependencies
  featureSummaries:
  - featureID: Helm
    hash: hFy1H2xM67yHdQb3PXdxBeDuy8P7n15UA887NV1q48I=
    lastAppliedTime: "2024-10-07T22:14:57Z"
    status: Provisioned
  helmReleaseSummaries:
  - releaseName: ingress-nginx
    releaseNamespace: ingress-nginx
    status: Managing
    valuesHash: 6aICjp6n9bmOrBjvtIoh8Wd6AnDGKRfXlhua0Q6KOGU=
```

</td>
<td>

**I can see that now the `ingress-ngnix-controller` deployment is back to running with 1 pod only on the Target Cluster**
```sh
➜  ~ kubectl get pod -A
NAMESPACE        NAME                                        READY   STATUS    RESTARTS   AGE
ingress-nginx    ingress-nginx-controller-5bfc858768-rkzg8   1/1     Running   0          85m
kube-system      aws-cloud-controller-manager-5z8zf          1/1     Running   0          112m
kube-system      calico-kube-controllers-695f6448bd-qkhkd    1/1     Running   0          113m
kube-system      calico-node-7xnkv                           1/1     Running   0          112m
kube-system      calico-node-gxgl5                           1/1     Running   0          112m
kube-system      coredns-6997b8f8bd-g9rqx                    1/1     Running   0          112m
kube-system      coredns-6997b8f8bd-pvm64                    1/1     Running   0          112m
kube-system      ebs-csi-controller-5c9db44f4f-7k4ld         5/5     Running   0          113m
kube-system      ebs-csi-controller-5c9db44f4f-jmmg5         5/5     Running   0          113m
kube-system      ebs-csi-node-rwxbb                          3/3     Running   0          112m
kube-system      ebs-csi-node-w52sd                          3/3     Running   0          112m
kube-system      kube-proxy-dfmxf                            1/1     Running   0          112m
kube-system      kube-proxy-sv5t6                            1/1     Running   0          112m
kube-system      metrics-server-7cc78958fc-nlxv2             1/1     Running   0          113m
projectsveltos   sveltos-agent-manager-67d6ffbd86-4mgwt      1/1     Running   0          112m
```

</td>
</tr>
</table>
