### ISSUE TITLE
Simplify BYO Templates

### ISSUE THREAD

**Issue by Schnitzel** [Mirantis/hmc#615]
Currently there is a mismatch of templates shipped by 2A and templates that want to be added by a 2A operator.

2A templates only need to define a Template (let's say a `ClusterTemplate`) and in there the following config:
```
spec:
  helm:
    chartName: aws-standalone-cp
    chartVersion: 0.0.2
```

the required `HelmChart` is then automatically created through `reconcileHelmChart`
https://github.com/Mirantis/hmc/blob/fb83d23c3942bfa02727d0cc90f76295fe68dca6/internal/controller/template_controller.go#L299
with the assumption that the HelmRepo is the default repo.

If someone wants to bring their own templates they need to currently create 3 objects, as described in the documentation: https://mirantis.github.io/project-2a-docs/template/byo-templates/ :
- `ClusterTemplate` <-- obvious
- `HelmRepository` <-- also makes sense
- `HelmChart` <-- feels unnecessary

The ClusterTemplate then has the following spec:

```
spec:
  helm:
    chartRef:
      kind: HelmChart
      name: custom-template-chart
      namespace: default
```

And the biggest issue is the lack of the version of helmchart defined, which needs to happen inside the HelmChart object:

```
kind: HelmChart
spec:
  chart: custom-template-chart-name
  sourceRef:
    kind: HelmRepository
    name: custom-templates-repo
  version: 0.2.0
```

So this means if a 2A operator wants to upgrade their BYO Templates, they not only need to create a new `ClusterTemplate` Object, but also a new `HelmChart` object for every new version. 
This feels honestly too cumbersome and should be simplified.

A possible solution would be to allow ClusterTemplate with this config:

```
spec:
  helm:
    chartName: aws-standalone-cp
    chartVersion: 0.0.2
    chartRepo: custom-templates-repo # new field
```

And 2A will then automatically reconcile the `HelmChart` object for it (so exactly the same as we also do for the 2A templates)
