### ISSUE TITLE
Use HelmChart instead of ServiceTemplate to feed chartName into Sveltos

### ISSUE THREAD

**Issue by wahabmk** [Mirantis/hmc#626]
The [chartName](https://github.com/Mirantis/hmc/blob/55bf573c6e69400008c5e9405272927a9fe6c4b8/internal/controller/multiclusterservice_controller.go#L213-L216) is being set using `ServiceTemplate`'s fields, which could have a custom name. E.g. The value of `.spec.helm.chartRef.name` in the template below:
```yaml
apiVersion: hmc.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: motel-template
  namespace: hmc-system
spec:
  helm:
    chartRef:
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmChart
      name: motel-0-1-0
      namespace: hmc-system
    chartVersion: 0.1.0
  providers: {}
```
If the name is custom as in this example, it creates an issue using it as the chart name in Sveltos. Therefore, the better option would be to fetch the `HelmChart` associated with this `ServiceTemplate` and use the fields in it to fetch the chart name like `.spec.chart` or `status.observedChartName`.
