### ISSUE TITLE
Credentials Distribution System

### ISSUE THREAD

**Issue by Schnitzel** [Mirantis/hmc#692]
Currently the `TemplateManagement` Object can distribute ClusterTemplates and ServiceTemplates to namespaces in order for them to be used in a `managedCluster` object in these namespaces.

See: https://github.com/Mirantis/hmc/blob/e38f5822cbefb05bfe00e200e90f68ca47f2592a/api/v1alpha1/templatemanagement_types.go#L42-L52

We would also need to be able to distribute credentials the same way. An example for clarification:

```
apiVersion: hmc.mirantis.com/v1alpha1
kind: TemplateManagement
metadata:
  name: hmc
spec:
  accessRules:
    - credential:
        - aws-cluster-identity-cred
      targetNamespaces:
        list:
          - default
```

would copy the credential `aws-cluster-identity-cred` to the namespace `default`.
