### ISSUE TITLE
Azure cloud provider only creates rules in the control plane NSG

### ISSUE THREAD

**Issue by gmlexx** [Mirantis/hmc#730]
I have an azure cluster created with the following manifest
```
apiVersion: hmc.mirantis.com/v1alpha1
kind: ManagedCluster
metadata:
  name: azure-reg1
  namespace: hmc-system
  labels:
    motel: "regional"
spec:
  template: azure-standalone-cp-0-0-3
  credential: azure-cluster-identity-cred
  config:
    controlPlaneNumber: 1
    workersNumber: 3
    location: "westus2"
    subscriptionID: "${AZURE_SUBSCRIPTION_ID}"
    controlPlane:
      vmSize: Standard_A4_v2
    worker:
      vmSize: Standard_A4_v2
    tenantID: "${AZURE_TENANT_ID}"
    clientID: "${AZURE_CLIENT_ID}"
    clientSecret: "${AZURE_CLIENT_SECRET}"
  servicesPriority: 100
  services:
    - template: ingress-nginx-4-11-3
      name: ingress-nginx
      namespace: ingress-nginx
    - name: cert-manager
      namespace: cert-manager
      template: cert-manager-1-16-1
      values: |
        crds:
          enabled: true
    - name: motel-regional
      namespace: motel
      template: motel-regional-0-1-1
      values: |
        victoriametrics:
          vmauth:
            ingress:
              host: reg-1.example.com
            credentials:
              username: motel
              password: motel
        grafana:
          ingress:
            enabled: true
            host: grafana.reg-1.example.com
        cert-manager:
          email: email@example.com

```

In result a nginx-ingress LB was created
```
ingress-nginx   ingress-nginx-controller                          LoadBalancer   10.103.165.119   4.155.90.207   80:30999/TCP,443:31409/TCP   75m
```

But the ingress-nginx-controller cannot receive any requests *probably* due to misconfiguration of ![azure-reg1-node-nsg NSG](https://github.com/user-attachments/assets/c774cd75-a8da-4261-b354-738b33d29b29)
