### ISSUE TITLE
Backups API missing permissions for `system:serviceaccount:hmc-system:hmc-controller-manager`

### ISSUE THREAD

**Issue by Schnitzel** [Mirantis/hmc#759]
Pulling the newest `main` branch and running `make dev-apply` results in a broken 2A installation, with the following error in the `hmc-controller-manager` pod:

```
E1210 16:15:54.377480 1 reflector.go:158] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.31.3/tools/cache/reflector.go:243: Failed to watch *v1alpha1.Backup: failed to list *v1alpha1.Backup: backups.hmc.mirantis.com is forbidden: User \"system:serviceaccount:hmc-system:hmc-controller-manager\" cannot list resource \"backups\" in API group \"hmc.mirantis.com\" at the cluster scope" logger="UnhandledError"
```

adding the following permissions to the ClusterRole `hmc-manager-role`, and restarting `hmc-controller-manager` pod
```
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - hmc.mirantis.com
    resources:
      - backups     
```
