### ISSUE TITLE
`providerContracts` and `providers` are not copied into target namespace when template managed through accessManagement

### ISSUE THREAD

**Issue by Schnitzel** [Mirantis/hmc#778]
assuming the following case:

```yaml
apiVersion: hmc.mirantis.com/v1alpha1
kind: ClusterTemplate
metadata:
  name: demo-aws-standalone-cp-0.0.1
  namespace: hmc-system
spec:
  helm:
    chartSpec:
      chart: demo-aws-standalone-cp
      interval: 10m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: 2a-demos
      version: 0.0.1
  providerContracts:
    bootstrap-k0smotron: v1beta1
    control-plane-k0smotron: v1beta1
    infrastructure-aws: v1beta2
  providers:
    - bootstrap-k0smotron
    - control-plane-k0smotron
    - infrastructure-aws
```

```yaml
apiVersion: hmc.mirantis.com/v1alpha1
kind: ClusterTemplateChain
metadata:
  name: demo-aws-standalone-cp-0.0.1
  namespace: hmc-system
spec:
  supportedTemplates:
    - name: demo-aws-standalone-cp-0.0.1
```

```yaml
apiVersion: hmc.mirantis.com/v1alpha1
kind: AccessManagement
metadata:
  name: hmc
spec:
  accessRules:
    - clusterTemplateChains:
        - demo-aws-standalone-cp-0.0.1
      targetNamespaces:
        list:
          - blue
```

the resulting `ClusterTemplate` in the `blue` namespace looks like this, see the missing `providerContracts` and `providers`

```yaml
apiVersion: hmc.mirantis.com/v1alpha1
kind: ClusterTemplate
metadata:
  name: demo-aws-standalone-cp-0.0.1
  namespace: blue
spec:
  helm:
    chartRef:
      kind: HelmChart
      name: demo-aws-standalone-cp-0.0.1
      namespace: hmc-system
```

this results to an error when trying to create a cluster:

```bash
NAMESPACE=blue CLUSTERNAME=prod1 /Users/michael/git/mirantis/hmc-demo/bin/envsubst-v1.4.2 -i managedClusters/aws/1-0.0.1.yaml | kubectl apply -f -
Error from server (Forbidden): error when creating "STDIN": admission webhook "validation.managedcluster.hmc.mirantis.com" denied the request: the ManagedCluster is invalid: template "demo-aws-standalone-cp-0.0.1" has no providers defined
```

this can be solved with defining the providers and contracts in the helm chart directly, but as we want support multiple places to define the provider and contracts we should probably also copy them into the target namespaces.
