### ISSUE TITLE
[bug] Panic when using ClusterTemplate delivered in namespace through AccessManagement

### ISSUE THREAD

**Issue by Schnitzel** [Mirantis/hmc#818]
**Describe the bug**
When delivering a ClusterTemplate through the HMC `AccessManagement` system the template looks like this:

```
apiVersion: hmc.mirantis.com/v1alpha1
kind: ClusterTemplate
metadata:
  name: demo-aws-standalone-cp-0.0.1
  namespace: blue
spec:
  helm:
    chartRef:
      kind: HelmChart
      name: demo-aws-standalone-cp-0.0.1
      namespace: hmc-system
  providerContracts:
    bootstrap-k0smotron: v1beta1
    control-plane-k0smotron: v1beta1
    infrastructure-aws: v1beta2
  providers:
    - bootstrap-k0smotron
    - control-plane-k0smotron
    - infrastructure-aws
```

see the `chartRef` and not the `chartSpec` definition, which makes sure as we already have a `HelmChart` definition and don't need to create a new HelmChart for each namespace.

Unfortunately when creating a `managedCluster` from this, the hmc controller panics:

```
runtime.sigpanic
/usr/local/go/src/runtime/signal_unix.go:881
github.com/Mirantis/hmc/internal/controller.(*ManagedClusterReconciler).updateCluster
/workspace/internal/controller/managedcluster_controller.go:315
github.com/Mirantis/hmc/internal/controller.(*ManagedClusterReconciler).reconcileUpdate
/workspace/internal/controller/managedcluster_controller.go:174
github.com/Mirantis/hmc/internal/controller.(*ManagedClusterReconciler).Reconcile
/workspace/internal/controller/managedcluster_controller.go:104
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:116
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:303
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224
2024-12-20T04:26:54Z ERROR Reconciler error {"controller": "managedcluster", "controllerGroup": "hmc.mirantis.com", "controllerKind": "ManagedCluster", "ManagedCluster": {"name":"blue-aws-dev1","namespace":"blue"}, "namespace": "blue", "name": "blue-aws-dev1", "reconcileID": "073e998d-e682-46ed-be3d-a684a0cb7587", "error": "panic: runtime error: invalid memory address or nil pointer dereference [recovered]"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224
```

It seems to be caused by this:
https://github.com/Mirantis/hmc/blob/cbd3fe38bc4bd634156ea4721f09fd4c2fd85a67/internal/controller/managedcluster_controller.go#L315

which basically expects that the chart is defined via `chartSpec` and doesn't understand that for delivered ClusterTemplates we will have a `chartRef` definition

**Expected behavior**
No panic
